language: csharp
solution: Identity.sln

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      sudo: false
      dotnet: 2.2
      mono: none
    - os: osx
      osx_image: xcode9
      dotnet: 2.2.300
      mono: none

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.nuget/packages

install:
  - dotnet restore -r $TRAVIS_OS_NAME-x64

script:
  - dotnet test
