name: Tests
on: [push]

jobs:
  linux_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['2.2.207', '2.2.402']
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: run tests
        run: dotnet test
  mac_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.402'
      - name: run tests
        run: dotnet test
  windows_tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.0.100'
      - name: Install coverage dependencies
        run: choco install opencover.portable codecov
      - name: run tests
        run: OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:test -excludebyfile:"*Identity.Tests*" -filter:"+[Tanker*]*" -output:".\coverage.xml" -oldstyle
      - name: upload coverage
        run: codecov -f "coverage.xml" -t ${{ secrets.CODECOV_TOKEN }}
